# the frequency that gazebo runs the simulation at
SIMULATION_FREQUENCY = 1000
SIMULATION_PERIOD = 1 / SIMULATION_FREQUENCY

MOTOR_NETWORKING_FREQUENCY = 300
MOTOR_NETWORKING_PERIOD = 1 / MOTOR_NETWORKING_FREQUENCY
MOTOR_TORQUE_CONSTANT = 0.1  # K_t

EPSILON = 0.001
