<?xml version="1.0"?>
<robot name="ALEX_Model_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="motor.xacro" ns="motor" />
  <xacro:include filename="common.xacro" ns="common" />
  <xacro:include filename="materials.xacro" />

  <!-- x = left, y = robot back, z = up -->
  <link name="world"></link>

  <xacro:motor.generate_motor prefix="main" />

  <joint name="fix" type="fixed">
    <parent link="world" />
    <child link="main_primary_cylinder" />
    <origin xyz="0 0 0.2" rpy="0 0 0" />
  </joint>

  <link name="propellor">
    <xacro:common.box width="0.05" depth="0.01" height="0.01" density="100" />
  </link>

  <joint name="propellor_joint" type="revolute">
    <parent link="main_primary_cylinder" />
    <child link="propellor" />
    <origin xyz="0 ${-1 * motor.thickness} 0" />
    <limit lower="${-100 * pi}" upper="${100 * pi}" effort="100000" velocity="1000000" />
    <axis xyz="0 1 0" />
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher"
        filename="libgazebo_ros_joint_state_publisher.so">
        <update_rate>100</update_rate>
        <joint_name>propellor_joint</joint_name>
    </plugin>
  </gazebo>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="propellor_joint">
      <command_interface name="effort">
        <param name="min">-1000</param>
        <param name="max">1000</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>../config/motor_controller.yaml</parameters>
      <controller_manager_name>controller_manager</controller_manager_name>
    </plugin>
  </gazebo>

</robot>
