<?xml version="1.0"?>
<robot name="ALEX_Model" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="common.xacro" />

  <gazebo reference="back_plate">
    <material>Gazebo/Orange</material>
  </gazebo>

  <link name="world"></link>

  <xacro:property name="back_plate_width" value="0.5" />
  <link name="back_plate">
    <xacro:box_visual_and_collision size="${back_plate_width} 0.01 0.2" xyz="0 0 0"/> 
    <xacro:generic_inertia />
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="world"/>
    <child link="back_plate"/>      
    <origin xyz="0 0 1" rpy="0 0 0"/>
  </joint>

  <xacro:property name="hip_width" value="0.2" />
  <link name="right_hip">
    <xacro:cylinder_visual_and_collision length="${hip_width}" radius="0.02" xyz="0.1 0 0" rpy="0 ${pi/2} 0" />
    <xacro:generic_inertia />
  </link>

  <gazebo reference="right_hip">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="base_to_right_hip" type="fixed">
    <parent link="back_plate"/>
    <child link="right_hip"/>
    <origin xyz="${back_plate_width / 2} 0 0"/>
  </joint>

  <xacro:property name="thigh_length" value="0.4" />
  <link name="right_thigh">
    <xacro:cylinder_visual_and_collision length="${thigh_length}" radius="0.1" xyz="0 0 -0.2" rpy="0 0 0" />
    <xacro:generic_inertia />
  </link>
  <gazebo reference="right_thigh">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_hip_to_thigh" type="revolute">
    <parent link="right_hip" />
    <child link="right_thigh" />
    <origin xyz="${hip_width / 2} 0 0" />
    <axis xyz="1 0 0" rpy="0 0 0"/>
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="100" velocity="1" />
  </joint>

  <xacro:property name="knee_width" value="0.15" />
  <link name="right_knee">
    <xacro:cylinder_visual_and_collision length="${knee_width}" radius="0.02" xyz="0 0 0" rpy="0 ${pi / 2} 0" />
    <xacro:generic_inertia />
  </link>
  <gazebo reference="right_knee">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_thigh_to_knee" type="fixed">
    <parent link="right_thigh" />
    <child link="right_knee" />
    <origin xyz="0 0 ${-1 * thigh_length}" />
  </joint>

  <xacro:property name="calf_length" value="0.3" />
  <link name="right_calf">
    <xacro:cylinder_visual_and_collision length="${calf_length}" radius="0.075" xyz="0 0 -0.15" rpy="0 0 0" />
    <xacro:generic_inertia />
  </link>
  <gazebo reference="right_calf">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_knee_to_calf" type="revolute">
    <parent link="right_knee" />
    <child link="right_calf" />
    <origin xyz="0 0 0" />
    <axis xyz="1 0 0" rpy="0 0 0"/>
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="100" velocity="1" />
  </joint>

  <xacro:property name="ankle_radius" value="0.02" />
  <link name="right_ankle">
    <xacro:cylinder_visual_and_collision length="0.1" radius="${ankle_radius}" xyz="0 0 0" rpy="0 ${pi / 2} 0" />
    <xacro:generic_inertia />
  </link>
  <gazebo reference="right_ankle">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_calf_to_ankle" type="fixed">
    <parent link="right_calf" />
    <child link="right_ankle" />
    <origin xyz="0 0 ${-1 * calf_length}" />
  </joint>
  
  <link name="right_foot">
    <xacro:box_visual_and_collision size="0.1 0.2 0.01" xyz="0 -0.05 0"/> 
    <xacro:generic_inertia />
  </link>
  <gazebo reference="right_foot">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_ankle_to_foot" type="fixed">
    <parent link="right_ankle" />
    <child link="right_foot" />
    <origin xyz="0 0 ${-1 * ankle_radius}" />
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher"
        filename="libgazebo_ros_joint_state_publisher.so">
        <update_rate>20</update_rate>
        <joint_name>right_hip_to_thigh</joint_name>
        <joint_name>right_knee_to_calf</joint_name>
    </plugin>
  </gazebo>

  <gazebo reference="right_foot">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>ALEX_Model/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>right_foot</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="right_foot">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu</topicName>
        <bodyName>right_foot</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>right_foot</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>


</robot>