<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="common.xacro" />

  <!-- taken from the datasheet -->
  <xacro:property name="thickness" value="0.075" />
  <xacro:property name="width" value="0.225" />
  <xacro:property name="height" value="0.120" />

  <!-- calculated values for urdf model -->
  <xacro:property name="radius" value="${0.120 / 2}" />
  <xacro:property name="inter_center_length" value="${width - 2 * radius}" />

  <xacro:property name="density" value="1000" />
  <xacro:macro name="single_cylinder" params="name">
    <link name="${name}"> 
      <xacro:cylinder radius="${radius}" length="${thickness}" rpy="${pi / 2} 0 0" density="${density}" color="blue" />
    </link>
  </xacro:macro>



  <!-- this macro requires a joint connecting to the ${prefix}_primary_cylinder -->
  <!-- and can connect off the link ${prefix}_secondary_cylinder -->
  <xacro:macro name="generate_motor" params="prefix">
    <!-- the circle that provides torque -->
    <xacro:single_cylinder name="${prefix}_primary_cylinder" />

    <!-- a rectangle that shows the connection space between circles -->
    <link name="${prefix}_motor_length">
      <xacro:box width="${inter_center_length}" depth="${thickness}" height="${height}" color="blue" density="${density}" />
    </link>

    <joint name="${prefix}_driving_to_length" type="fixed">
      <parent link="${prefix}_primary_cylinder" />
      <child link="${prefix}_motor_length" />
      <origin xyz="${inter_center_length / 2} 0 0" />
    </joint>

    <!-- the circle that takes in the Ethernet input -->
    <xacro:single_cylinder name="${prefix}_secondary_cylinder" />

    <joint name="${prefix}_length_to_signal" type="fixed">
      <parent link="${prefix}_motor_length" />
      <child link="${prefix}_secondary_cylinder" />
      <origin xyz="${inter_center_length / 2} 0 0" rpy="0 0 0" />
    </joint>    
  </xacro:macro>

</robot>

