<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="common.xacro" />
  <xacro:include filename="motor.xacro" ns="motor" />

  <xacro:property name="length" value="0.230" />
  <xacro:property name="thickness" value="0.0853" />
  <xacro:property name="width" value="0.1016" />

  <xacro:macro name="generate_thigh" params="prefix">
    <xacro:motor.generate_motor prefix="${prefix}_hip"/>

    <link name="${prefix}_thigh">
      <xacro:box_visual_and_collision size="${length} ${width} ${thickness}" xyz="0 0 0" />
      <xacro:generic_inertia />
    </link>  

    <joint name="${prefix}_motor_to_thigh" type="fixed">
      <parent link="${prefix}_hip_secondary_cylinder" />
      <child link="${prefix}_thigh" />
      <origin xyz="${length / 2} 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:motor.generate_motor prefix="${prefix}_knee" />

    <joint name="${prefix}_thigh_to_knee" type="fixed">
      <parent link="${prefix}_thigh" />
      <child link="${prefix}_knee_primary_cylinder" />
      <origin xyz="${length / 2} 0 0" rpy="0 0 0" />
    </joint>
  </xacro:macro>  
</robot>

