<?xml version="1.0"?>
<robot name="ALEX_Model_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="motor.xacro" ns="motor" />
  <xacro:include filename="common.xacro" ns="common" />
  <xacro:include filename="materials.xacro" />

  <xacro:property name="steeldensity" value="7850" />
  <xacro:property name="motor_diameter" value="0.085" />
  <xacro:property name="motor_length" value="0.075" />
  <xacro:property name="inner_diameter" value="0.06" />
  <xacro:property name="inner_length" value="0.055" />
  <xacro:property name="base_length" value="0.09" />
  <xacro:property name="attachment_height" value="0.035" />
  <xacro:property name="attachment_diameter" value="0.025" />
  <xacro:property name="motor_offset" value="${-base_length / 2 + motor_length - inner_length / 2}" />


  <!-- x = left, y = robot back, z = up -->
  <link name="world"></link>
  <link name="base">
    <xacro:common.box width="0.15" depth="0.15" height="0.015" density="${steeldensity}" />
  </link>

  <joint name="fix" type="fixed">
    <parent link="world" />
    <child link="base" />
    <origin xyz="0 0 ${0.015/2}" rpy="0 0 0" />
  </joint>

  <gazebo reference="bottom_motor_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="bottom_motor_link">
    <visual>
      <xacro:common.cylinder-geom length="${inner_length}" radius="${inner_diameter / 2}"/>
    </visual>
    <collision>
      <xacro:common.cylinder-geom length="${inner_length}" radius="${inner_diameter / 2}"/>
    </collision>
    <xacro:common.cylinder-inertia length="${inner_length}" radius="${inner_diameter / 2}" density="${steeldensity}" />
  </link>

  <joint name="bottom_motor" type="revolute">
    <parent link="base" />
    <child link="bottom_motor_link" />
    <origin xyz="0 0 ${(inner_length + 0.02)/ 2}" />
    <limit lower="${-100 * pi}" upper="${100 * pi}" effort="100000" velocity="1000000" />
    <axis xyz="0 0 -1" />
    <dynamics damping="0.01" friction="0.00"/>
  </joint>

  <gazebo reference="top_motor_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="top_motor_link">
    <visual>
      <xacro:common.cylinder-geom length="0.03" radius="0.02" rpy="0 ${pi / 2} 0" xyz="0.05 0 0"/>
    </visual>
    <visual>
      <xacro:common.cylinder-geom length="0.1" radius="0.01" rpy="0 0 0" xyz="0.05 0 0.05"/>
    </visual>
    <visual>
      <xacro:common.cylinder-geom length="${inner_length}" radius="${inner_diameter / 2}" rpy="0 ${pi / 2} 0"/>
    </visual>
    <collision>
      <xacro:common.cylinder-geom length="${inner_length}" radius="${inner_diameter / 2}" rpy="0 ${pi / 2} 0"/>
    </collision>
    <xacro:common.cylinder-inertia length="${inner_length}" radius="${inner_diameter / 2}" density="${steeldensity}" rpy="0 ${pi / 2} 0" />
  </link>

  <joint name="top_motor" type="revolute">
    <parent link="bottom_motor_link" />
    <child link="top_motor_link" />
    <origin xyz="${-motor_offset} 0 ${inner_length + attachment_height}" />
    <limit lower="${-1000 * pi}" upper="${1000 * pi}" effort="10000" velocity="10000" />
    <axis xyz="1 0 0" />
    <dynamics damping="0.01" friction="0.00"/>
  </joint>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="bottom_motor">
      <command_interface name="effort">
        <param name="min">-1000</param>
        <param name="max">1000</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="top_motor">
      <command_interface name="effort">
        <param name="min">-1000</param>
        <param name="max">1000</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>../config/twin_controller.yaml</parameters>
    </plugin>
  </gazebo>

</robot>
