<?xml version="1.0"?>
<robot name="ALEX_Model_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="materials.xacro" />
  <xacro:include filename="common.xacro" />
  <xacro:include filename="back.xacro" ns="back" />
  <xacro:include filename="motor.xacro" ns="motor" />
  <xacro:include filename="leg/leg.xacro" ns="leg" />

  <xacro:property name="prefix" value="left" />

  <!-- x = left, y = robot back, z = up -->
  <link name="world"></link>
  <xacro:back.generate_back />

  <xacro:leg.generate_leg prefix="${prefix}" />

  <joint name="left_rear_motor" type="revolute">
    <parent link="back_plate" />
    <child link="left_rear_primary_cylinder" />
    <origin xyz="${back.rear_spacing / 2} ${(back.plate_thickness + motor.thickness) / 2} ${(-1 * back.plate_height / 2) + motor.radius}" rpy="0 0 0" />
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="400" velocity="1" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

   <gazebo>
      <plugin name="gazebo_ros_joint_state_publisher"
          filename="libgazebo_ros_joint_state_publisher.so">
          <update_rate>100</update_rate>
          <joint_name>left_rear_motor</joint_name>
          <joint_name>left_hip_motor</joint_name>
          <joint_name>left_knee_to_calf</joint_name>
      </plugin>
    </gazebo>
</robot>
