<?xml version="1.0"?>
<robot name="ALEX_Model_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="materials.xacro" />
  <xacro:include filename="common.xacro" />
  <xacro:include filename="back.xacro" ns="back" />
  <xacro:include filename="motor.xacro" ns="motor" />
  <xacro:include filename="calf.xacro" ns="calf" />
  <xacro:include filename="calf_to_ankle.xacro" ns="calf_to_ankle" />

  <!-- x = left, y = robot back, z = up -->
  <link name="world"></link>
  <xacro:back.generate_back />
  <xacro:motor.generate_motor prefix="left_rear" />
  
  <joint name="left_rear_motor" type="revolute">
    <parent link="left_connection" />
    <child link="left_rear_primary_cylinder" />
    <origin xyz="0 ${motor.thickness / 2} 0" rpy="0 0 0" />
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="400" velocity="1" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <xacro:property name="rear_center_to_edge_length" value="0.130" />
  <link name="left_rear_limb">
    <xacro:box_visual_and_collision size="${rear_center_to_edge_length} ${motor.thickness} ${motor.radius * 2}" xyz="0 0 0"/>
    <xacro:generic_inertia />
  </link>

  <joint name="left_rear_limb_to_motor_joint" type="fixed">
    <parent link="left_rear_secondary_cylinder"/>
    <child link="left_rear_limb"/>
    <origin xyz="${rear_center_to_edge_length / 2} 0 0" rpy="0 0 0" />
  </joint>

  <xacro:property name="side_plate_length" value="0.260" />
  <xacro:property name="side_plate_height" value="0.06" />
  <xacro:property name="side_plate_thickness" value="0.028" />
  <link name="left_side_plate">
    <xacro:box_visual_and_collision size="${side_plate_thickness} ${side_plate_length} ${side_plate_height}" xyz="0 0 0" />
    <xacro:generic_inertia />
  </link>

  <joint name="left_side_plate_to_rear_limb" type="fixed">
    <parent link="left_rear_limb" />
    <child link="left_side_plate" />
    <origin xyz="${rear_center_to_edge_length / 2 - side_plate_thickness / 2} ${motor.height / 2 - side_plate_length / 2} 0" />
  </joint>

  <xacro:motor.generate_motor prefix="left_hip"/>

  <joint name="left_hip_motor" type="revolute">
    <parent link="left_side_plate" />
    <child link="left_hip_primary_cylinder" />
    <origin xyz="${-1 * motor.thickness / 2} ${-1 * side_plate_length / 2} 0" rpy="0 ${pi/2} ${pi / 2}" />
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="400" velocity="1" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <xacro:property name="thigh_length" value="0.230" />
  <xacro:property name="thigh_thickness" value="0.0853" />
  <xacro:property name="thigh_width" value="0.1016" />

  <link name="left_thigh">
    <xacro:box_visual_and_collision size="${thigh_length} ${thigh_width} ${thigh_thickness}" xyz="0 0 0" />
    <xacro:generic_inertia />
  </link>  

  <joint name="left_motor_to_thigh" type="fixed">
    <parent link="left_hip_secondary_cylinder" />
    <child link="left_thigh" />
    <origin xyz="${thigh_length / 2} 0 0" rpy="0 0 0"/>
  </joint>

  <xacro:motor.generate_motor prefix="left_knee" />

  <joint name="left_thigh_to_knee" type="fixed">
    <parent link="left_thigh" />
    <child link="left_knee_primary_cylinder" />
    <origin xyz="${thigh_length / 2} 0 0" rpy="0 0 0" />
  </joint>

 <xacro:calf_to_ankle.generate_calf_to_ankle prefix="left" />

  <joint name="left_knee_to_calf" type="revolute">
    <parent link="left_knee_secondary_cylinder" />
    <child link="left_calf_plate" />
    <origin xyz="${calf.plate_length / 2} ${(motor.thickness + calf.plate_width) / 2} 0" rpy="0 0 0" />
    <limit lower="${-pi / 2}" upper="${pi / 2}" effort="400" velocity="1" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

</robot>
