controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    hip_joint_controller:
      type: effort_controllers/JointGroupEffortController

    knee_joint_controller:
      type: effort_controllers/JointGroupEffortController

hip_joint_controller:
  ros__parameters:
    joints:
      - right_hip_to_thigh

knee_joint_controller:
  ros__parameters:
    joints:
      - right_knee_to_calf
