controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - right_knee_to_calf
