controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    propellor_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

propellor_controller:
  ros__parameters:
    joints:
      - propellor_joint
