controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    propellor_controller:
      type: effort_controllers/JointGroupEffortController

propellor_controller:
  ros__parameters:
    joints:
      - propellor_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort