<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="../common.xacro" />

  <xacro:property name="extension_length" value="0.140" />
  <xacro:property name="extension_radius" value="0.013" />
  
  <xacro:property name="length" value="0.035" />  
  <xacro:property name="radius" value="0.070" />
  
  <xacro:property name="side_length" value="0.110" />
  <xacro:property name="side_thickness" value="0.044" />
  <xacro:property name="side_width" value="0.0175" />
  
  <xacro:property name="base_length" value="0.3155" />
  <xacro:property name="base_width" value="0.120" />
  <xacro:property name="base_thickness" value="0.013" />
  

  <xacro:macro name="generate_ankle" params="prefix">
    <link name="${prefix}_ankle_extension">
      <xacro:cylinder radius="${extension_radius}" length="${extension_length}" rpy="0 ${pi / 2} 0" />
    </link>

    <link name="${prefix}_ankle">
      <xacro:cylinder radius="${radius}" length="${length}" rpy="${pi / 2} 0 0" />
    </link>

    <joint name="${prefix}_ankle_extension_to_ankle" type="fixed">
      <parent link="${prefix}_ankle_extension" />
      <child link="${prefix}_ankle" />
      <origin xyz="${extension_length / 2} 0 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}_ankle_side">
      <xacro:box width="${side_length}" depth="${side_width}" height="${side_thickness}" />
    </link>

    <joint name="${prefix}_ankle_to_ankle_side" type="fixed">
      <parent link="${prefix}_ankle" />
      <child link="${prefix}_ankle_side" />
      <origin xyz="${side_length / 2} ${(length + side_width) / 2} 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}_ankle_base">
      <xacro:box width="${base_thickness}" depth="${base_width}" height="${base_length}" />
    </link>

    <joint name="${prefix}_ankle_side_to_base" type="fixed">
      <parent link="${prefix}_ankle_side" />
      <child link="${prefix}_ankle_base" />
      <origin xyz="${side_length / 2} ${base_width / 2} ${-1 * base_length / 4}" rpy="0 0 0" />
    </joint>
  </xacro:macro>

  
</robot>

